name: app_kit
description: "A new Flutter project."
version: 0.0.1


environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.1.0
  flutter_spinkit: ^5.2.1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0